import { PrismaClient } from "@prisma/client";

const main = async () => {
  const prisma = new PrismaClient();

  // id being generated by postgres
  return await prisma.shipment.create({ data: { id: 2, data: "my data" } });
};

main();
